name: GenericsLib
author: JC The Pants
main: com.jcwhatever.bukkit.generic.GenericsLib
version: 0-beta
depend: [ProtocolLib]
softdepend: [Vault]
commands:
    jcg:
        description: Base command for jcGenerics
        usage: |
            ERROR!