name: NucleusFramework
author: JCThePants
main: com.jcwhatever.nucleus.BukkitPlugin
version: 0.3-beta
softdepend: [Vault, WorldEdit]
commands:
    nucleusframework:
        aliases: [n, nuc, nucleus]
        description: Base command for NucleusFramework
        usage: |
            ERROR!
    neconomy:
        aliases: [necon, economy, econ, money]
        description: Economy commands.
        usage: |
            ERROR!
    nfriends:
        aliases: [friends, friend, f]
        description: Friend commands.
        usage: |
            ERROR!