name: GenericsLib
author: JCThePants
main: com.jcwhatever.bukkit.generic.BukkitPlugin
version: 0.0-beta
softdepend: [Vault]
commands:
    g:
        aliases: [gen, generics]
        description: Base command for GenericsLib
        usage: |
            ERROR!