name: GenericsLib
author: JC The Pants
main: com.jcwhatever.bukkit.generic.GenericsLib
version: 0-beta
softdepend: [Vault]
commands:
    generics:
        description: Base command for jcGenerics
        usage: |
            ERROR!