name: GenericsLib
author: JCThePants
main: com.jcwhatever.generic.BukkitPlugin
version: 0.0-beta
softdepend: [Vault, WorldEdit]
commands:
    g:
        aliases: [gen, generics]
        description: Base command for GenericsLib
        usage: |
            ERROR!
    geconomy:
        aliases: [gecon, economy, econ, money]
        description: Economy commands.
        usage: |
            ERROR!