name: GenericsLib
author: JCThePants
main: com.jcwhatever.bukkit.generic.GenericsLib
version: 0.0-beta
softdepend: [Vault]
commands:
    generics:
        description: Base command for GenericsLib
        usage: |
            ERROR!